FROM neo4j:5.19.0

# Move APOC JAR file from labs directory to plugins directory
RUN mv /var/lib/neo4j/labs/apoc-5.19.0-core.jar /var/lib/neo4j/plugins/

# Set environment variables
ENV NEO4J_AUTH neo4j/pleaseletmein
ENV NEO4J_dbms_security_procedures_unrestricted my.extensions.example,my.procedures.*,apoc.*
ENV NEO4J_dbms_security_procedures_allowlist apoc.*

# Install and Update CA Certs
RUN apt install -y ca-certificates
RUN mkdir -p /usr/local/share/ca-certificates
COPY DSOCA50.pem /usr/local/share/ca-certificates
COPY DSOVisibilityCA.pem /usr/local/share/ca-certificates
RUN mv /usr/local/share/ca-certificates/DSOCA50.pem /usr/local/share/ca-certificates/DSOCA50.crt
RUN mv /usr/local/share/ca-certificates/DSOVisibilityCA.pem /usr/local/share/ca-certificates/DSOVisibilityCA.crt
RUN update-ca-certificates
